# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Replace numeric-numeric
#'
#' Replace numeric values by other numeric values.
#'
#' Function iterates through \code{elems} and identifies a replacement in \code{rep} by
#' matching the elements to \code{set}
#'
#' @param elems numeric vector of to be replaced elements
#' @param set numeric vector containing the unique set of elems
#' @param rep numeric vector of same length as set containing the replacement values
#'
#' @return numeric vector of same length as \code{elems} containing the replacement values
#'
#' @export
replace_nn <- function(elems, set, rep) {
    .Call('f_utils_replace_nn', PACKAGE = 'f.utils', elems, set, rep)
}

#' Replace numeric-character
#'
#' Replace numeric values by character values.
#'
#' Function iterates through \code{elems} and identifies a replacement in \code{rep} by
#' matching the elements to \code{set}
#'
#' @param elems numeric vector of to be replaced elements
#' @param set numeric vector containing the unique set of elems
#' @param rep character vector of same length as set containing the replacement values
#'
#' @return character vector of same length as \code{elems} containing the replacement values
#'
#' @export
replace_nc <- function(elems, set, rep) {
    .Call('f_utils_replace_nc', PACKAGE = 'f.utils', elems, set, rep)
}

#' Replace character-numeric
#'
#' Replace character values by numeric values.
#'
#' Function iterates through \code{elems} and identifies a replacement in \code{rep} by
#' matching the elements to \code{set}
#'
#' @param elems character vector of to be replaced elements
#' @param set character vector containing the unique set of elems
#' @param rep numeric vector of same length as set containing the replacement values
#'
#' @return character vector of same length as \code{elems} containing the replacement values
#'
#' @export
replace_cn <- function(elems, set, rep) {
    .Call('f_utils_replace_cn', PACKAGE = 'f.utils', elems, set, rep)
}

#' Replace character-character
#'
#' Replace character values by other character values.
#'
#' Function iterates through \code{elems} and identifies a replacement in \code{rep} by
#' matching the elements to \code{set}
#'
#' @param elems character vector of to be replaced elements
#' @param set character vector containing the unique set of elems
#' @param rep character vector of same length as set containing the replacement values
#'
#' @return character vector of same length as \code{elems} containing the replacement values
#'
#' @export
replace_cc <- function(elems, set, rep) {
    .Call('f_utils_replace_cc', PACKAGE = 'f.utils', elems, set, rep)
}

count_lines <- function(filename) {
    .Call('f_utils_count_lines', PACKAGE = 'f.utils', filename)
}

strsplit_c <- function(line, delim) {
    .Call('f_utils_strsplit_c', PACKAGE = 'f.utils', line, delim)
}

readbig <- function(filename, delim = '\t', nlines = 0L) {
    .Call('f_utils_readbig', PACKAGE = 'f.utils', filename, delim, nlines)
}

